import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import Hero from '../container/Hero/hero';

const inter = Inter({ subsets: ['latin'] })

import { 
  Hero
} from '../container';

import {
  Navbar,
  NavbarTwo
} from '../components';

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={`${styles.main} ${inter.className}` + ' header'}>
          {/* <Navbar /> */}
          <NavbarTwo />
        </header>

        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.description}>
            <Hero />
          </div>
        </main>

        <footer>

        </footer>
      </div>
    </>
  )
}
